[package]
name = "dxo-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "DXO deep learning core engine (tensor, autograd, backends)"
publish = false

[dependencies]
rand = { workspace = true }
titan-backend-cpu = { git = "https://github.com/ai4waifu/titan.rs.git", branch = "dev" }
titan-hal = { git = "https://github.com/ai4waifu/titan.rs.git", branch = "dev" }
titan-types = { git = "https://github.com/ai4waifu/titan.rs.git", branch = "dev" }
